# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sandhya Chandramohan
email: sandhya2392@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pet projects and side hustles
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://csandhya.in" # the base hostname & protocol for your site
twitter_username: sandhya2392
github_username:  sandhya2392

# Build settings
markdown: kramdown
